import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { Subscription } from '../../../core/models/saas.models';
import { SaasService } from '../../../core/services/saas.service';
import { TenantContextService } from '../../../core/services/tenant-context.service';

@Component({selector:'app-tenant-subscription',standalone:true,imports:[CommonModule],host:{class:'sgs-dark-view block'},template:`
<div class="mx-auto max-w-4xl space-y-5"><div><p class="text-sm font-medium text-brand-500">Administration</p><h1 class="text-2xl font-semibold text-gray-900 dark:text-white">Mon abonnement</h1><p class="text-sm text-gray-500">{{context.tenant()?.name||'Établissement courant'}}</p></div>
@if(subscription){<section class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-white/[.03]"><div class="flex flex-wrap justify-between gap-4"><div><p class="text-sm text-gray-500">Plan actuel</p><h2 class="text-2xl font-semibold dark:text-white">{{subscription.planName||'Plan SGS'}}</h2></div><span class="h-fit rounded-full bg-success-50 px-3 py-1 text-sm text-success-700">{{subscription.status}}</span></div><dl class="mt-6 grid gap-4 sm:grid-cols-3"><div><dt class="text-xs uppercase text-gray-500">Début</dt><dd class="mt-1 dark:text-white">{{subscription.startsAt|date:'dd/MM/yyyy'}}</dd></div><div><dt class="text-xs uppercase text-gray-500">Fin</dt><dd class="mt-1 dark:text-white">{{subscription.endsAt?(subscription.endsAt|date:'dd/MM/yyyy'):'Sans échéance'}}</dd></div><div><dt class="text-xs uppercase text-gray-500">Tenant</dt><dd class="mt-1 dark:text-white">{{subscription.tenantName||context.tenant()?.code||'—'}}</dd></div></dl></section>} @else if(loading){<p class="text-gray-500">Chargement…</p>} @else {<p class="rounded-xl border border-warning-200 bg-warning-50 p-4 text-warning-700">{{error||'Aucun abonnement actif.'}}</p>}</div>`})
export class TenantSubscriptionComponent implements OnInit{subscription:Subscription|null=null;loading=true;error='';constructor(private api:SaasService,public context:TenantContextService){}ngOnInit(){this.api.currentSubscription().subscribe({next:v=>{this.subscription=v;this.loading=false},error:e=>{this.error=e.error?.message||'Abonnement indisponible.';this.loading=false}})}}
